hr/urls.py
from django.urls import path
from hr import views
urlpatterns=[
    path('signin',views.loginview.as_view(),name="signin"),
    path('index',views.dashboard.as_view(),name="index"),
    path('logout',views.signout.as_view(),name="logout"),
    path('create/',views.Addcategory.as_view(),name="category"),
    path('remove/<int:pk>',views.categoryremove.as_view(),name="category-del"),
    path('add',views.Addjob.as_view(),name="addjob"),
    path('removejob/<int:pk>',views.jobremove.as_view(),name="job-rem"),
    #path('jobview/<int:pk>',views.jobdetail.as_view(),name="job-det"),
    path('joblist/',views.joblist.as_view(),name="list"),
    path('jobedit/<int:pk>',views.jobupdate.as_view(),name="edit"),
    path('viewjobs/',views.Viewjobs.as_view(),name="viewjob"),
    path('application/<int:pk>',views.Seeker.as_view(),name="hrview")
]

jobseeker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hr/', include("hr.urls")),
    path('user/', include("user.urls")),
    path('api/', include("api.urls"))

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    Name=models.CharField(max_length=20,unique=True)

    def __str__(self):
        return self.Name
    
class job(models.Model):
    jobname= models.CharField(max_length=200)
    company_name=models.CharField(max_length=200)
    experience=models.PositiveIntegerField()
    salary=models.PositiveIntegerField()
    qualification=models.CharField(max_length=200)
    skill=models.CharField(max_length=200)
    poster=models.ImageField(upload_to="poster")
    category=models.ForeignKey(Category,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.jobname
    
class student(models.Model):
    email=models.CharField(max_length=200)
    contact=models.PositiveIntegerField()
    age=models.PositiveIntegerField()
    qualification=models.CharField(max_length=200)
    skill=models.CharField(max_length=200)
    resume=models.FileField(upload_to="files",null=True)
    experience=models.CharField(max_length=20)
    options=(("male","male"),("female","female"))
    gender=models.CharField(max_length=20,choices=options,default="male")
    user=models.OneToOneField(User,on_delete=models.DO_NOTHING,null=True,related_name="profile")

    def __str__(self):
        return self.name

class applications(models.Model):
    jobs=models.ForeignKey(job,on_delete=models.CASCADE)
    student=models.ForeignKey(User,on_delete=models.CASCADE)
    options=(("pending","pending"),("rejected","rejected"),("processing","processing"))
    status=models.CharField(max_length=30,choices=options,default="pending")

hr/models.py
from django.db import models

# Create your models here.

hr/forms.py
from django import forms
from app.models import Category,job

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField()

class categoryform(forms.ModelForm):
    class Meta:
        model=Category
        fields=["Name"]

class jobform(forms.ModelForm):
    class Meta:
        model=job
        #exclude=(fieldname,)
        fields='__all__'

hr/views.py
from django.shortcuts import render,redirect
from django.views.generic import View,FormView,TemplateView,CreateView,ListView,DeleteView,UpdateView,DetailView
from django.contrib.auth import authenticate,login,logout
from hr.forms import LoginForm,categoryform,jobform
from django.urls import reverse_lazy
from app.models import Category,job,applications,student
# Create your views here.

class loginview(FormView):
    template_name="login.html"
    form_class=LoginForm

    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)
        if form.is_valid():
            u_name=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            user_obj=authenticate(request,username=u_name,password=pwd)
            if user_obj:
                login(request,user_obj)
                if request.user.is_superuser:
                    return redirect("index")
                else:
                    return redirect("userindex")
            else:
                print("failed")
            return render(request,"login.html",{"form":form})
        
class dashboard(TemplateView):
    template_name="index.html"

class signout(View):
    def get(self,request,*args,**kwargs):
        logout(request)
        return redirect("signin")

class Addcategory(CreateView,ListView):
    template_name="category.html"
    form_class=categoryform
    success_url=reverse_lazy("category")
    context_object_name="data"
    model=Category

#class categoryremove(DeleteView):
    #template_name="category.html"
    #model=Category
    #success_url=reverse_lazy("category")

class categoryremove(View):
    def get(self,request,*args,**kwargs):
        id=kwargs.get("pk")
        Category.objects.get(id=id).delete()
        return redirect("category")
    
class Addjob(CreateView):
    template_name="job_add.html"
    form_class=jobform
    model=job
    success_url=reverse_lazy("addjob")
    #context_object_name="qs"

class jobremove(View):
    def get(self,request,*args,**kwargs):
        id=kwargs.get("pk")
        job.objects.get(id=id).delete()
        return redirect("addjob")
    
#class jobdetail(View):
    #def get(self,request,*args,**kwargs):
        #id=kwargs.get("pk")
        #detail=job.objects.filter(id=id)
        #return render(request,"jobview.html",{"detail":detail})
    
class joblist(ListView):
    template_name="job_list.html"
    model=job
    context_object_name="jobs"

class jobupdate(UpdateView):
    template_name="jobview.html"
    form_class=jobform
    success_url=reverse_lazy("index")
    model=job

class Viewjobs(View):
    def get(self,request,*args,**kwargs):
        data=applications.objects.all()
        return render(request,"viewjob.html",{"data":data})
    
class Seeker(DetailView):
    # def get(self,request,*args,**kwargs):
    #     id=kwargs.get("pk")
    #     student.objects.get(id=id)
    #     return render(request,"userdetails.html")
    template_name="userdetails.html"
    context_object_name="data"
    model=student
    success_url=reverse_lazy('hrview')
    

hr/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jobs</title>

    <link rel="stylesheet" href="style.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</head>

<body class="overflow-x-hidden">

    <!-- {%block body_block%} -->

    <div class="">
        <div class="row ">
            <div class="col-2 px-5 pt-5 bg-dark vh-100" id="sticky-sidebar">
                <div class="sticky-top">
                    <div class="nav flex-column">
                        <p class="fw-bold fs-4 text-center text-light">Admin </p>
                        <hr class="text-light">
                        <a href="#"
                            class="text-light text-decoration-none mt-4 p-2 fs-6 btn btn-dark text-start">Home</a>
                        <a href="{% url 'category' %}"
                            class="text-light text-decoration-none p-2 fs-6 btn btn-dark text-start">Category</a>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Jobs
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'addjob' %}">Add job</a></li>
                                <li><a class="dropdown-item" href="{% url 'list' %}">View job</a></li>
                            </ul>
                        </div>
                        <a href="{% url 'viewjob' %}"
                            class="text-light text-decoration-none p-2 fs-6 btn btn-dark text-start">Applications</a>
                        <a href="{% url 'logout' %}"
                            class="text-light text-decoration-none p-2 fs-6 btn btn-dark text-start">Log out</a>
                    </div>
                </div>
            </div>
            <div class="col mx-2 " id="main">
                <div class="mt-5"></div>
                <h3 class="fw-bold">Hello Admin<!--{{request.user}},--></h3>
                <br><br>

                <br><br>

                {%block mainblock%}


                {%endblock%}

            </div>
        </div>
    </div>

    <!-- {%endblock%} -->


</body>

</html>

hr/templates/category.html
{%extends 'base.html'%}

{%block mainblock%}

<div class="row mt-5">
    <div class="col-2"></div>
    <div class="col-8">
        <form action="" method="post">
            {%csrf_token%}
        <h1>Category</h1>
            <hr class="mb-5 w-25 border-4">
            <div class="d-flex mt-4">
                <input type="text" name="Name" class="form-control ">
                <button type="submit" class="btn btn-dark ms-2">Add</button>
            </div>
        </form>
        <table class="table table-bordered mt-4">
            <thead class="table-dark ">
                <tr>
                    <th>Category</th>
                    <th>Actions</th>
                    
                </tr>
            </thead>
            <tbody class="text-center">
                {%for d in data%}
              <tr>
                    <td>{{d.Name}}</td>
                    <td><a href="{% url 'category-del' d.id %}"><i class="fa-solid fa-trash"></i></a></td>
                    
              </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
    <div class="col-2"></div>
</div>
{%endblock%}

hr/templates/index.html
{%extends 'base.html'%}

{%block mainblock%}

<div class="d-flex justify-content-evenly">
    <a href="{% url 'category' %}" class="btn btn-dark w-25">Category</a>
    <a href="{% url 'addjob' %}" class="btn btn-dark w-25">Jobs</a>
    <a href="#" class="btn btn-dark w-25">Applications</a>
</div>

{% endblock %}

hr/templates/job_add.html
{%extends 'base.html'%}

{%block mainblock%}


<div class="container d-flex justify-content-around">
    
    <form action="" method="post" enctype="multipart/form-data" class="bg-white w-75 rounded-3">
        {% csrf_token %}
        <p class="fw-bold fs-4 ">Add Job</p>
        <hr class="mb-1 w-25 border-4">
        <div class=" row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12 "><label for="">Title :</label><input type="text"
                    name="jobname" class="form-control"></div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label for="">Category :</label>
                
                <select class="form-select" name="category" id="id_category">
                    <option value="{{form.category}}"></option>
                </select>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Company
                    :</label><input type="text" name="company_name" class="form-control"></div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Experience
                    :</label><input type="text" name="experience" class="form-control"></div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Salary
                    :</label><input type="text" name="salary" class="form-control"></div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Poster
                    :</label><input type="file" name="poster" class="form-control"></div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Skill :</label><input
                    type="text" name="skill" class="form-control"></div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Qualification
                    :</label><input type="text" name="qualification" class="form-control"></div>

            <div class="text-center">
                <button class="btn btn-dark mt-4 mb-4 w-50">Add Job</button>
                <br>
            </div>


        </div>
    </form>
</div>

{%endblock%}

hr/templates/job_list.html
{% extends "base.html" %}
{%block mainblock%}
{% for i in jobs %}
<div class="card mb-3 w-75 ">
    <div class="row g-0">
      <div class="col-md-4">
        {%if 'i.poster' %}
        <img src="{{ i.poster.url }}" class="img-fluid rounded-start" alt="...">
        {%endif%}  
    </div>
      <div class="col-md-5">
        <div class="card-body">
            

          <h5 class="card-title">Job Name :{{i.jobname}}</h5>
          <h5 class="card-title">Company Name :{{i.company_name}}</h5>
          <!--<h5 class="card-title">{{i.experience}}</h5>
          <h5 class="card-title">{{i.salary}}</h5>
          <h5 class="card-title">{{i.qualification}}</h5>-->
          <h5 class="card-title">Skill Req :{{i.skill}}</h5>
          <!--<h5 class="card-title">{{i.title}}</h5>-->

          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="col-md-3">
        <a href="{% url 'edit' i.id %}" class="btn btn-primary my-2 ">View & Update</a>
        <br>
        <a href="{% url 'job-rem' i.id %}" class="btn btn-primary my-2 ">Delete</a>
        <br>
      </div>
    </div>
  </div>
{%endfor%}
{%endblock%}

hr/templates/jobview.html
{%extends 'base.html'%}

{%block mainblock%}


<div class="container d-flex justify-content-around">
    
    <form action="" method="post" enctype="multipart/form-data" class="bg-white w-75 rounded-3">
        {% csrf_token %}
        <p class="fw-bold fs-4 ">Add Job</p>
        <hr class="mb-1 w-25 border-4">
        <div class=" row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12 "><label for="">Title :</label><input type="text"
                    name="jobname" value="{{form.jobname.value}}" class="form-control"></div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label for="">Category :</label>
                
                <select class="form-select" name="category" value="{{form.category.value}}" id="id_category">
                    <option selected>---------option>
                    <option value={{form.category}}></option>
                </select>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Company
                    :</label><input type="text" name="company_name" value="{{form.company_name.value}}" class="form-control"></div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Experience
                    :</label><input type="text" name="experience" value="{{form.experience.value}}" class="form-control"></div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Salary
                    :</label><input type="text" name="salary" value="{{form.salary.value}}" class="form-control"></div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Poster
                    :</label><input type="file" name="poster"  class="form-control">{{form.poster.value}}</div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Skill :</label><input
                    type="text" name="skill" value="{{form.skill.value}}" class="form-control"></div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Qualification
                    :</label><input type="text" name="qualification" value="{{form.qualification.value}}" class="form-control"></div>

            <div class="text-center">
                <button class="btn btn-dark mt-4 mb-4 w-50">Add Job</button>
                <br>
            </div>


        </div>
    </form>
</div>

{%endblock%}

hr/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jobs</title>

    <link rel="stylesheet" href="style.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</head>

<body class="overflow-x-hidden bg-secondary">



    <div class="container d-flex justify-content-around">
        <form action="" method="post" class="bg-white m-5 p-5 w-50 rounded-3">
            {%csrf_token%}
            <p class="fw-bold fs-4 "> Login</p>
            <hr class="mb-5 w-25 border-4">
            <div class="text-center">
                <input type="text" class="form-control  text-center" name="username" placeholder="enter username"><br>
                <input type="text" class="form-control  text-center" name="password" placeholder="Password"><br>

                <button type="submit" class="btn btn-dark w-50 mt-5 mb-5">Login</button>
                <br>
                <p>Or<br>Create an Account</p>
                <a href="#" class="btn btn-outline-dark w-25">Register</a>
            </div>
        </form>
    </div>

  


</body>

</html>

hr/templates/userdetails.html
{%extends 'base.html'%}

{%block mainblock%}

<div class="container my-5">
    <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title fw-bold text-center">{{username.request.data}}</h5>
            <p class="card-text text-center">{{data.email}}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Qualification: {{data.qualification}}</li>
            <li class="list-group-item">Skills: {{data.skill}}</li>
            <li class="list-group-item">Experience: {{data.experience}}</li>
            
        </ul>
        <div class="card-body">
            <a href="data.resume.url" download="" class="card-link btn btn-dark btn-sm"> Resume Download</a>
            
        </div>
    </div>
    </div>
    

{% endblock %}

hr/templates/viewjob.html
{%extends 'base.html'%}

{%block mainblock%}
{% for i in data %}


<div class="card mb-3 w-75  ">
    <div class="row g-0">
        <div class="col-md-4 m-3">

            <img src="{{ i.jobs.poster.url }}" class="img-fluid rounded-start" alt="...">

        </div>
        <div class="col-md-5">
            <div class="card-body">


                <h2 class="card-title">Seeker :{{i.student}}</h2>
                <h5 class="card-title">Role :{{i.jobs.jobname}}</h5>


                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                 <a href="{% url  'hrview' i.student.id %}" class="btn btn-primary my-2 ">Seeker details</a> <!--cant see the seeker detail because of url -->
            </div>
        </div>



    </div>
</div>
{%endfor%}

{% endblock %}

<!-- {% for i in data %}
{{i.jobs}}
{{i.student}}
{%endfor%} -->